/*
 * this file is generated by grimoirejs-cauldron
 */

// build version
export const __VERSION__ = "2.0.0";

// full package name
export const __NAME__ = "grimoirejs-math";

const shortening = /^[Gg]rimoire(?:js|JS)?-(.*)$/.exec(__NAME__);
// dafault registerd namespace
export const __NAMESPACE__ = shortening ? shortening[1] : __NAME__;
